# Permalinks
permalink:        pretty

# Setup
url:              http://rulonder.github.io/rulonder/index.html

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            random bits

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Some thoughts tranformed into programs and bits.


# The tags listed as entries in the sidebar
sidebar_tags:     [software, aerospace]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Raúl Núñez'
  twitter:        raulnss
  github:         rulonder
  photo:          /public/img/bird.jpeg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Raul ,a never ending learner.This is my personal webpage. let me introduce myself: I am a technology appasionate, always looking to the edge of the current technologies and how they can be applied to solve daily problems.
    
    